"use client";

import { FormEvent } from "react";
import { Button } from "@/components/ui/button";
import {
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { ScrollText } from "lucide-react";

interface ReceiptingAgreementStepProps {
  onAgree: () => void; // Called when user clicks "Agree"
  charityName: string; // Name of the Charity
  onBack: () => void; // Called when user clicks "Back"
}

export function ReceiptingAgreementStep({
  onAgree,
  charityName,
  onBack,
}: ReceiptingAgreementStepProps) {
  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    onAgree();
  };

  return (
    <>
      <DialogHeader>
        <div className="flex items-center">
          <DialogTitle>Agreement</DialogTitle>
        </div>
        <DialogDescription>
          Please review the following terms before agreeing.
        </DialogDescription>
      </DialogHeader>

      <form onSubmit={handleSubmit}>
        <div className="border rounded-lg">
          <div className="max-h-64 overflow-y-auto p-4 text-sm scrollbar-thin space-y-4">
            {/* Intro */}
            <div className="flex items-start mb-2">
              <ScrollText className="h-5 w-5 text-primary mr-2" />
              <p className="font-medium">
                This AGREEMENT (“Agreement”) is entered into by and between{" "}
                <span className="bg-primary/10 px-1 rounded">
                  {charityName}
                </span>{" "}
                (“Charity”) and{" "}
                <span className="bg-primary/10 px-1 rounded">DigiDov</span>. By
                accessing or using DigiDov’s platform and services, the Charity
                agrees to be bound by the terms of this Agreement.
              </p>
            </div>

            {/* 1. DEFINITIONS */}
            <div>
              <h2 className="font-semibold">1. DEFINITIONS</h2>
              <p className="mt-2">
                <strong>Tax Receipt:</strong> An official receipt generated by
                DigiDov containing all information required under United States
                and Canadian regulatory standards for charitable donations.
                These receipts are sent to Donors via email and made available
                for download in the Donor’s online dashboard.
              </p>
              <p>
                <strong>Crypto Donation:</strong> A transfer of cryptocurrency
                made by a Donor directly from the Donor’s wallet to the
                Charity’s wallet on a decentralized blockchain network.
              </p>
              <p>
                <strong>Processing Fee:</strong> A fee equal to three percent
                (3%) that is automatically deducted from each Crypto Donation to
                cover DigiDov’s technology, administrative infrastructure,
                record keeping, and digital signature processing services for
                Tax Receipts.
              </p>
            </div>

            {/* 2. SERVICES PROVIDED */}
            <div>
              <h2 className="font-semibold">2. SERVICES PROVIDED</h2>
              <p className="mt-2">
                DigiDov provides technology and services solely to facilitate:
              </p>
              <ul className="list-disc list-inside mt-1">
                <li>
                  The transmission of Crypto Donations from Donors to the
                  Charity;
                </li>
                <li>
                  Automatic deduction of the 3% Processing Fee from each
                  donation;
                </li>
                <li>
                  Recording and management of donation transactions, including
                  generating unique transaction identifiers and corresponding
                  Tax Receipt identifiers;
                </li>
                <li>
                  Issuance of official Tax Receipts, sent via email and made
                  available for download to the Donor; and
                </li>
                <li>
                  Online dashboards that allow the Charity and its Donors to
                  monitor transactions, view Tax Receipts, and access detailed
                  reporting.
                </li>
              </ul>
              <p className="mt-2">
                DigiDov is not responsible for the custody, management,
                conversion, or protection of any funds.
              </p>
            </div>

            {/* 3. AUTHORIZATION AND STANDING DELEGATION */}
            <div>
              <h2 className="font-semibold">
                3. AUTHORIZATION AND STANDING DELEGATION
              </h2>
              <p className="mt-2">
                The Charity hereby grants DigiDov a standing authorization to
                digitally sign all Tax Receipts issued on the Charity’s behalf.
                This authorization is effective as of the Effective Date of this
                Agreement and remains in effect until terminated by either Party
                in accordance with the termination provisions of this Agreement.
              </p>
            </div>

            {/* 4. TRANSACTION REPORTING */}
            <div>
              <h2 className="font-semibold">
                4. TRANSACTION REPORTING AND ACCOUNTING INFORMATION
              </h2>
              <p className="mt-2">
                DigiDov shall provide the Charity with detailed transaction
                statements through the Charity’s online dashboard. These
                statements shall, for each Crypto Donation, include:
              </p>
              <ul className="list-disc list-inside mt-1">
                <li>The gross donation amount;</li>
                <li>The 3% Processing Fee deduction;</li>
                <li>The resulting net donation amount;</li>
                <li>Unique transaction identifiers; and</li>
                <li>Corresponding Tax Receipt identifiers.</li>
              </ul>
              <p className="mt-2">
                The information available on the dashboard shall serve as the
                official record for all processed transactions and fee
                deductions for the Charity’s accounting, auditing, and
                regulatory compliance purposes.
              </p>
            </div>

            {/* 5. CONFIDENTIALITY */}
            <div>
              <h2 className="font-semibold">5. CONFIDENTIALITY</h2>
              <p className="mt-2">
                Each Party agrees to maintain the confidentiality of all
                Confidential Information disclosed under this Agreement and to
                use such information solely for performing its obligations
                hereunder. Confidential Information includes, but is not limited
                to, donor data, transaction records, proprietary systems, and
                processes.
              </p>
            </div>

            {/* 6. LIMITATION OF LIABILITY AND INDEMNIFICATION */}
            <div>
              <h2 className="font-semibold">
                6. LIMITATION OF LIABILITY AND INDEMNIFICATION
              </h2>
              <p className="mt-2">
                <strong>Zero Cumulative Liability:</strong> To the fullest
                extent permitted by law, DigiDov shall have zero (0) cumulative
                liability for any claims, losses, damages, or liabilities
                arising out of or related to this Agreement.
              </p>
              <p>
                <strong>Scope of DigiDov’s Responsibility:</strong> The Charity
                acknowledges that DigiDov’s responsibility is limited solely to
                facilitating the transmission of Crypto Donations and accurate
                record keeping. DigiDov shall have no liability for the custody,
                management, conversion, or protection of the funds.
              </p>
              <p>
                <strong>Indemnification:</strong> The Charity shall indemnify,
                defend, and hold harmless DigiDov, its affiliates, officers,
                directors, employees, and agents from any and all claims,
                losses, or damages arising out of or related to the Charity’s
                failure to secure or manage its cryptocurrency funds.
              </p>
            </div>

            {/* 7. DISPUTE RESOLUTION */}
            <div>
              <h2 className="font-semibold">7. DISPUTE RESOLUTION</h2>
              <p className="mt-2">
                The Parties agree to resolve any dispute arising out of or
                related to this Agreement in good faith through direct
                negotiation. If such dispute cannot be resolved through
                negotiation, the Parties shall attempt to resolve it through
                mediation. If mediation fails, the dispute shall be submitted to
                binding arbitration before any legal action may be initiated.
              </p>
            </div>

            {/* 8. TERM AND TERMINATION */}
            <div>
              <h2 className="font-semibold">8. TERM AND TERMINATION</h2>
              <p className="mt-2">
                This Agreement shall commence on the Effective Date and shall
                continue for an initial term of one (1) year, automatically
                renewing for successive one-year periods unless terminated as
                provided herein.
              </p>
              <p>
                <strong>Termination for Cause:</strong> Either Party may
                terminate this Agreement for a material breach if the breaching
                Party fails to cure such breach within thirty (30) days after
                receiving written notice.
              </p>
              <p>
                <strong>Termination Without Cause:</strong> Either Party may
                terminate this Agreement without cause upon thirty (30) days’
                written notice to the other Party.
              </p>
              <p>
                <strong>Effect of Termination:</strong> Termination of this
                Agreement shall not affect any rights or liabilities accrued
                prior to the effective date of termination.
              </p>
            </div>

            {/* 9. MISCELLANEOUS */}
            <div>
              <h2 className="font-semibold">9. MISCELLANEOUS</h2>
              <p className="mt-2">
                <strong>Entire Agreement:</strong> This Agreement constitutes
                the entire agreement between the Parties with respect to the
                subject matter herein, superseding all prior or contemporaneous
                communications.
              </p>
              <p>
                <strong>Governing Law:</strong> This Agreement shall be governed
                by and construed in accordance with the laws of the jurisdiction
                in which DigiDov is organized, without regard to conflict-of-law
                rules.
              </p>
              <p>
                <strong>Severability:</strong> If any provision of this
                Agreement is held invalid or unenforceable, the remaining
                provisions shall remain in full force and effect.
              </p>
              <p>
                <strong>Amendments:</strong> Any modifications to this Agreement
                must be in writing and signed by authorized representatives of
                both Parties.
              </p>
              <p>
                <strong>Assignment:</strong> Neither Party may assign or
                transfer this Agreement, in whole or in part, without the prior
                written consent of the other Party; except, that DigiDov may
                assign or transfer this Agreement in the event of a merger,
                acquisition, corporate reorganization, or sale of all or
                substantially all of its assets. In such an event, the assigning
                Party shall provide written notice to the other Party. This
                Agreement shall be binding on and inure to the benefit of the
                Parties and their respective successors and permitted assigns.
              </p>
            </div>

            {/* 10. INTELLECTUAL PROPERTY OWNERSHIP */}
            <div>
              <h2 className="font-semibold">
                10. INTELLECTUAL PROPERTY OWNERSHIP
              </h2>
              <p className="mt-2">
                <strong>DigiDov’s IP:</strong> All right, title, and interest in
                and to the DigiDov platform, software, trademarks, trade names,
                and any related or underlying technology (including any
                modifications or derivatives), are and shall remain the
                exclusive property of DigiDov.
              </p>
              <p>
                <strong>Charity’s IP:</strong> The Charity retains all right,
                title, and interest in and to its own trademarks, logos,
                proprietary content, and other intellectual property. No rights
                or licenses are granted to DigiDov under this Agreement except
                as needed to perform the services described herein.
              </p>
            </div>

            {/* 11. WARRANTY DISCLAIMER */}
            <div>
              <h2 className="font-semibold">11. WARRANTY DISCLAIMER</h2>
              <p className="mt-2">
                EXCEPT AS EXPRESSLY PROVIDED HEREIN, DIGIDOV PROVIDES ITS
                PLATFORM AND SERVICES ON AN “AS IS” AND “AS AVAILABLE” BASIS,
                AND HEREBY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS
                OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
                WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
                AND NON-INFRINGEMENT. DIGIDOV DOES NOT WARRANT THAT THE SERVICES
                WILL BE UNINTERRUPTED, ERROR-FREE, OR COMPLETELY SECURE, OR THAT
                DEFECTS WILL BE CORRECTED.
              </p>
            </div>

            {/* 12. FORCE MAJEURE */}
            <div>
              <h2 className="font-semibold">12. FORCE MAJEURE</h2>
              <p className="mt-2">
                Neither Party shall be liable for any failure or delay in the
                performance of its obligations under this Agreement if such
                failure or delay is caused by events beyond the Party’s
                reasonable control, including but not limited to acts of God,
                war, terrorism, riots, embargoes, acts of civil or military
                authorities, fires, floods, accidents, strikes, or shortages of
                transportation facilities, fuel, energy, labor, or materials.
                The affected Party shall promptly notify the other Party of the
                occurrence of a force majeure event and shall use commercially
                reasonable efforts to mitigate its effects and resume
                performance as soon as practicable.
              </p>
            </div>

            {/* 13. PUBLICITY / MARKETING */}
            <div>
              <h2 className="font-semibold">13. PUBLICITY / MARKETING</h2>
              <p className="mt-2">
                Neither Party shall publicly reference or use the other Party’s
                name, trademarks, or logos in any marketing, press releases,
                promotional materials, or public announcements without the prior
                written consent of the other Party, which may be withheld at the
                Party’s sole discretion. However, DigiDov may include the
                Charity’s name and/or logo in a general list of customers for
                promotional purposes, provided that DigiDov does not expressly
                or implicitly endorse the Charity or misrepresent the nature of
                the relationship.
              </p>
            </div>

            {/* 14. NO JOINT VENTURE / PARTNERSHIP */}
            <div>
              <h2 className="font-semibold">
                14. NO JOINT VENTURE / PARTNERSHIP
              </h2>
              <p className="mt-2">
                Nothing in this Agreement shall be construed to create a joint
                venture, partnership, agency, or fiduciary relationship between
                the Parties. Both Parties are independent contractors, and
                neither Party has the authority to bind the other to any
                obligations.
              </p>
            </div>

            {/* 15. NO THIRD-PARTY BENEFICIARIES */}
            <div>
              <h2 className="font-semibold">
                15. NO THIRD-PARTY BENEFICIARIES
              </h2>
              <p className="mt-2">
                This Agreement is entered into solely for the benefit of the
                Parties hereto and their respective successors and permitted
                assigns. No provision of this Agreement is intended to confer
                any rights, benefits, remedies, or claims upon any person or
                entity not a Party to this Agreement.
              </p>
            </div>

            {/* 16. NOTICES */}
            <div>
              <h2 className="font-semibold">16. NOTICES</h2>
              <p className="mt-2">
                Any notice or other communication required or permitted to be
                given under this Agreement shall be in writing and delivered by
                email to the addresses designated by each Party. Notices shall
                be deemed effective upon the sending Party’s receipt of a
                confirmation (via read receipt or a written acknowledgment from
                the recipient) indicating that the recipient received and
                reviewed the email. Each Party shall promptly notify the other
                Party of any changes to its designated email address for notices
                under this Agreement.
              </p>
            </div>

            {/* 17. EXPORT COMPLIANCE (IF APPLICABLE) */}
            <div>
              <h2 className="font-semibold">17. EXPORT COMPLIANCE</h2>
              <p className="mt-2">
                Each Party represents and warrants that it will comply with all
                applicable export and import control laws and regulations in
                providing and using the Services. The Charity shall not access
                or use DigiDov’s platform in violation of any such laws or
                regulations. Without limiting the foregoing, each Party agrees
                that it shall not directly or indirectly export, re-export, or
                transfer any technical data acquired from the other Party under
                this Agreement to any destination or person restricted or
                prohibited by any export control regulations, unless properly
                authorized by the relevant government authority.
              </p>
            </div>

            {/* 18. ELECTRONIC SIGNATURES AND EXECUTION */}
            <div>
              <h2 className="font-semibold">
                18. ELECTRONIC SIGNATURES AND EXECUTION
              </h2>
              <p className="mt-2">
                The Parties consent to the use of electronic signatures or
                click-through acceptance and agree that either method shall be
                deemed valid and enforceable. The Parties further agree that
                this Agreement and any subsequent amendments or modifications
                may be entered into electronically, and that any such electronic
                signatures or manifestations of acceptance shall have the same
                force and effect as an original ink-signed document.
              </p>
            </div>

            <p className="text-sm mt-4">
              By clicking &quot;Agree&quot; below, you confirm that you have
              read and consent to the terms of this Agreement.
            </p>
          </div>
        </div>

        {/* Navigation buttons */}
        <div className="mt-4 flex justify-between">
          <Button type="button" variant="outline" onClick={onBack}>
            Back
          </Button>
          <Button type="submit">Agree</Button>
        </div>
      </form>
    </>
  );
}
